### ISSUE TITLE
Hi, are there any updates?

### ISSUE THREAD

**Issue by nullifiedaccount3** [call-a3/api-blueprint-to-postman#1]

**Comment by call-a3** [comment]
I started this project because we were using blueprint and postman in the company I work at. However, we've dropped blueprint for now in favour of a custom solution. It wasn't my preferred solution, but what'ya gonna do right?!

Anyway, since we're not using blueprint for the moment this project has been on hold. I'd still like to work on it though... And if I know there's an interest for it, that might be an extra motivation to work on this some more. What's your use case?

**Comment by nullifiedaccount3** [comment]
Hi, thanks for the reply. My usecase was to build documentation and postman collection from `.apib` file. For that purpose I use `aglio` and `apiary2postman`. Here are the two tools I install and use currently in my documentation build process:

``` bash
#!/usr/bin/env bash

git clone https://github.com/apiaryio/drafter
cd drafter
git checkout b3dce8d # This is the commit for release 0.1.9
git submodule update --init --recursive # Get all the dependencies needed for compile
./configure
make
sudo make install

npm install aglio
pip install apiary2postman
```

As you can see this `apiary2postman` depends on `drafter`. Drafter was updated few versions further and apiary2postman couldn't accommodate the new changes, so they are using drafter 0.19.

I'm using aglio for building documentation.

Let me know if you want to build a dependency free tool that can translate apib to postman json.
